' -----------------------------------------------------------------------
' Template source file generated by piklab

' -----------------------------------------------------------------------
' Configuration bits: adapt to your setup and needs

' main program
Sub main()
    ' << insert code >>
    Do while 1 ' loop forever
    Loop
End Sub
