serverCore.o: serverCore.c
	gcc -Wall -c serverCore.c
socketaction.o : socketaction.c
	gcc -Wall -c socketaction.c
core.o : core.c
	gcc -Wall -c core.c
serverManager.o : serverManager.c
	gcc -Wall -c serverManager.c
userdata.o : userdata.c
	gcc -Wall -c userdata.c
message.o : message.c
	gcc -Wall -c message.c
server.o : server.c
	gcc -Wall -c server.c
