// generated 2006/10/14 15:24:36 EDT by luigi@tuxy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- chesslan.glade
// for gtk 2.10.6 and gtkmm 2.10.2
//
// Please modify the corresponding derived classes in ./src/chesslan1.cc


#if defined __GNUC__ && __GNUC__ < 3
#error This program will crash if compiled with g++ 2.x
// see the dynamic_cast bug in the gtkmm FAQ
#endif //
#include "config.h"
/*
 * Standard gettext macros.
 */
#ifdef ENABLE_NLS
#  include <libintl.h>
#  undef _
#  define _(String) dgettext (GETTEXT_PACKAGE, String)
#  ifdef gettext_noop
#    define N_(String) gettext_noop (String)
#  else
#    define N_(String) (String)
#  endif
#else
#  define textdomain(String) (String)
#  define gettext(String) (String)
#  define dgettext(Domain,Message) (Message)
#  define dcgettext(Domain,Message,Type) (Message)
#  define bindtextdomain(Domain,Directory) (Domain)
#  define _(String) (String)
#  define N_(String) (String)
#endif
#include <gtkmmconfig.h>
#if GTKMM_MAJOR_VERSION==2 && GTKMM_MINOR_VERSION>2
#include <sigc++/compatibility.h>
#define GMM_GTKMM_22_24(a,b) b
#else //gtkmm 2.2
#define GMM_GTKMM_22_24(a,b) a
#endif //
#include "chesslan1_glade.hh"
#include <gdk/gdkkeysyms.h>
#include <gtkmm/accelgroup.h>
#include "menubar1.hh"
#include "notebook1.hh"

chesslan1_glade::chesslan1_glade(
) : Gtk::Window(Gtk::WINDOW_TOPLEVEL)
{  chesslan1 = this;
   gmm_data = new GlademmData(get_accel_group());
   menubar1 = Gtk::manage(new class menubar1(gmm_data));
   notebook1 = Gtk::manage(new class notebook1(gmm_data));
   vbox1 = Gtk::manage(new class Gtk::VBox(false, 0));
   vbox1->pack_start(*menubar1, Gtk::PACK_SHRINK, 0);
   vbox1->pack_start(*notebook1);
   chesslan1->set_border_width(1);
   chesslan1->set_title(_("ChessLan"));
   chesslan1->set_default_size(630,470);
   chesslan1->set_modal(false);
   chesslan1->property_window_position().set_value(Gtk::WIN_POS_NONE);
   chesslan1->set_resizable(true);
   chesslan1->property_destroy_with_parent().set_value(false);
   chesslan1->add(*vbox1);
   vbox1->show();
   chesslan1->show();
}

chesslan1_glade::~chesslan1_glade()
{  delete gmm_data;
}
