// generated 2006/10/14 15:24:36 EDT by luigi@tuxy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- chesslan.glade
// for gtk 2.10.6 and gtkmm 2.10.2
//
// Please modify the corresponding derived classes in ./src/menubar1.hh and./src/menubar1.cc

#ifndef _MENUBAR1_GLADE_HH
#  define _MENUBAR1_GLADE_HH

// Since all your widgets were private I made them all public.
// To differentiate between accessable (e.g. entries, output labels)
// and unaccessible widgets (e.g. static labels, containers)
// you should use the 'visibility' property (only visible in C++ mode)


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/menubar.h>
#include <gtkmm/imagemenuitem.h>
#include <gtkmm/menuitem.h>
#include <gtkmm/menu.h>
#include <gtkmm/image.h>

class menubar1_glade : public Gtk::MenuBar
{  
public:
        
        class Gtk::MenuBar * menubar1;
        class Gtk::ImageMenuItem * new1;
        class Gtk::ImageMenuItem * open1;
        class Gtk::ImageMenuItem * save1;
        class Gtk::ImageMenuItem * save_as1;
        class Gtk::MenuItem * separatormenuitem1;
        class Gtk::ImageMenuItem * quit1;
        class Gtk::Menu * file1_menu;
        class Gtk::MenuItem * file1;
        class Gtk::Image * image7;
        class Gtk::ImageMenuItem * preferences1;
        class Gtk::Menu * settings1_menu;
        class Gtk::MenuItem * settings1;
        class Gtk::Image * image8;
        class Gtk::ImageMenuItem * about1;
        class Gtk::Menu * help1_menu;
        class Gtk::MenuItem * help1;
protected:
        
        menubar1_glade(GlademmData *gmm_data);
        
        ~menubar1_glade();
private:
        virtual void on_new1_activate() = 0;
        virtual void on_open1_activate() = 0;
        virtual void on_save1_activate() = 0;
        virtual void on_save_as1_activate() = 0;
        virtual void on_quit1_activate() = 0;
        virtual void on_preferences1_activate() = 0;
        virtual void on_about1_activate() = 0;
};
#endif
