// generated 2006/10/14 15:24:37 EDT by luigi@tuxy.(none)
// using glademm V2.6.0
//
// DO NOT EDIT THIS FILE ! It was created using
// glade-- chesslan.glade
// for gtk 2.10.6 and gtkmm 2.10.2
//
// Please modify the corresponding derived classes in ./src/notebook1.hh and./src/notebook1.cc

#ifndef _NOTEBOOK1_GLADE_HH
#  define _NOTEBOOK1_GLADE_HH

// Since all your widgets were private I made them all public.
// To differentiate between accessable (e.g. entries, output labels)
// and unaccessible widgets (e.g. static labels, containers)
// you should use the 'visibility' property (only visible in C++ mode)


#if !defined(GLADEMM_DATA)
#define GLADEMM_DATA 
#include <gtkmm/accelgroup.h>

class GlademmData
{  
        
        Glib::RefPtr<Gtk::AccelGroup> accgrp;
public:
        
        GlademmData(Glib::RefPtr<Gtk::AccelGroup> ag) : accgrp(ag)
        {  
        }
        
        Glib::RefPtr<Gtk::AccelGroup>  getAccelGroup()
        {  return accgrp;
        }
};
#endif //GLADEMM_DATA

#include <gtkmm/notebook.h>
#include "frame1.hh"
#include "statusbar1.hh"
#include <gtkmm/box.h>
#include <gtkmm/label.h>
#include <gtkmm/separator.h>
#include "treeview1.hh"
#include <gtkmm/scrolledwindow.h>
#include "toolbar1.hh"

class notebook1_glade : public Gtk::Notebook
{  
public:
        
        class Gtk::Notebook * notebook1;
        class frame1 * frame1;
        class statusbar1 * statusbar1;
        class Gtk::VBox * vbox4;
        class Gtk::Label * label2;
        class Gtk::Label * label4;
        class Gtk::HSeparator * hseparator1;
        class Gtk::Label * label3;
        class Gtk::Label * label5;
        class Gtk::VBox * vbox3;
        class treeview1 * treeview1;
        class Gtk::ScrolledWindow * scrolledwindow1;
        class toolbar1 * toolbar1;
        class Gtk::VBox * vbox2;
        class Gtk::HBox * hbox1;
        class Gtk::Label * nlabel1;
protected:
        
        notebook1_glade(GlademmData *gmm_data);
        
        ~notebook1_glade();
};
#endif
